Failed to execute action: test_server()
Traceback (most recent call last):
  File "/home/limyreth/pyautomate/pyautomate/main.py", line 19, in <module>
    application.run()
  File "/home/limyreth/pyautomate/pyautomate/application.py", line 39, in run
    self._execute_path(dfa, options.exact)
  File "/home/limyreth/pyautomate/pyautomate/application.py", line 153, in _execute_path
    eval(action, vars(self._config))
  File "<string>", line 1, in <module>
  File "/home/limyreth/.texttest/tmp/tt.26Jun101031.6542/tt/stop_at_first_failed_action/auto.py", line 34, in test_server
    print(this_will_stop_execution)
NameError: global name 'this_will_stop_execution' is not defined
